<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Associated course external functions and service definitions.
 *
 * @package    block_associated_course
 * @category   external
 * @copyright  2019 ckf
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;

$functions = array(
    'block_data_screen_platform_overview' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'platform_overview',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Platform overview',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_attribute_course' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'attribute_course',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Attribute course API',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_tags' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_tags',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get the course tag list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_invalid_course' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'invalid_course',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get the invalid_courses',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_category' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_category',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get course categoris list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_access_table' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'access_table',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get access statistics data',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_access_chart' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'access_chart',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get access statistics data',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_college_list' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'college_list',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get college list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_college_detail' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'college_detail',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get college information',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_teacher_list' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'teacher_list',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get teacher list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_dept' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_dept',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get department list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_teacher_detail' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'teacher_detail',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get teacher detail',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_semester' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_semester',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get semester list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_course_detail' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'course_detail',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get course statistics data',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_activity_analysis' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'activity_analysis',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Course activity analysis',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_personal_analysis' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'personal_analysis',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Personal analysis',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_personal_detail' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'personal_detail',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Personal detail',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_role' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_role',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get roles',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_get_activities_completion_status' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'get_activities_completion_status',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Get activities completion status',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_set_role' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'set_role',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Set role sort',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_search_course' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'search_course',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Search course',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_search_courses' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'search_courses',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Search courses',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_zoom' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'zoom',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'zoom count',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_zoomuser' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'zoomuser',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'zoomuser list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_zoommod' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'zoommod',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'zoommod list',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_online_courses' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'online_courses',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Online courses',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_online_learning' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'online_learning',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Real-time student population',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_active_7days' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'active_7days',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Real-time student population',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_course_teachinfo' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'course_teachinfo',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Course teaching info',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_network_teach' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'network_teach',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Network teaching info',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
    'block_data_screen_day_active' => array(
        'classname'     => 'block_data_screen_external',
        'methodname'    => 'day_active',
        'classpath'     => 'blocks/data_screen/externallib.php',
        'description'   => 'Someday active course',
        'type'          => 'read',
        'ajax'          => true,
        'capabilities'  => 'block/data_screen:statistics',
    ),
);